project:
  type: website

website:
  title: "Proper Test Index Blog"
  navbar:
    right:
      - icon: github
        href: https://github.com/ak-gupta
format:
  html:
    theme:
      - flatly
      - brand
    css: styles.css



