project:
  type: website

website:
  title: "proper-test-index"
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/
      - icon: twitter
        href: https://twitter.com
format:
  html:
    theme:
      - flatly
      - brand
    css: styles.css



